### ISSUE TITLE
urh-2.0.4 build error: src/urh/dev/native/lib/hackrf.cpp:607:10: fatal error: config.h: No such file or directory

### ISSUE THREAD

**Issue by yarda** [jopohl/urh#435]
_Please use this template for bug reports. If you have a feature request or question just delete everything and write as you like._
## Expected Behavior
No build error

## Actual Behavior
build error:
...
src/urh/dev/native/lib/hackrf.cpp:607:10: fatal error: config.h: No such file or directory

## Steps to Reproduce the Problem

  1. Build for Fedora rawhide (29) (https://koji.fedoraproject.org/koji/taskinfo?taskID=26833486)
  2.
  3.

Build log: https://kojipkgs.fedoraproject.org//work/tasks/3487/26833487/build.log

## Platform Specifications

  - Python Version: python-3.6.5-4
  - Operating System: Fedora rawhide (29)
  - Version of URH: 2.0.4
  - URH was installed: __from source__ 

I tried to build with hackrf-2017.02.1 and hackrf-2018.01.1. Unfortunately, there is no config.h, nor the HACKRF_HAS_MULTI_DEVICE defined.

**Comment by yarda** [comment]
Same problem with the RTLSDR_HAS_BANDWIDTH for rtl-sdr.

**Comment by jopohl** [comment]
That's strange...I just had a look in the [latest source release](https://github.com/jopohl/urh/archive/v2.0.4.tar.gz)  and the ``` config.h ``` is located in ``` src/urh/dev/native/includes/ ```. I also just installed the 2.0.4 version of URH on arch linux and did not experience any issues.

Where do you download the sources from? Maybe you need to tell Fedora something about the new include path (``` src/urh/dev/native/includes/  ```)?

**Comment by yarda** [comment]
Hmm, it seems it isn't in the .tar.gz:
https://github.com/jopohl/urh/archive/v2.0.4.tar.gz

But it is in the zip.

**Comment by yarda** [comment]
Hmm, I re-downloaded the tar.gz and it's there. Maybe the download was corrupted.

**Comment by yarda** [comment]
Ah, sorry, got it, it seems to be fault in our build procedure, sorry for noise.
